prefix owl:   <http://www.w3.org/2002/07/owl#> 
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix obo:  <http://purl.obolibrary.org/obo/>

SELECT ?iri ?lab ?def
WHERE {
  ?iri rdf:type owl:DatatypeProperty.
  OPTIONAL{?iri obo:IAO_0000115 ?def}.
  OPTIONAL{?iri rdfs:label ?lab}.
}